version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./AI-Frontend:/app/frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - .:/app/backend
    depends_on:
      - frontend
